version: '2.2'

x-defaults: &defaults
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: '1m'
      max-file: '5'

services:

  hello-world-website:
    image: httpd:2.4
    hostname: hello-world-website
    ports:
      - "24242:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/
