version: '2.2'

x-defaults: &defaults
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: '1m'
      max-file: '5'

services:

  nexus:
    image: sonatype/nexus3
    hostname: nexus
    ports:
      - "28081:8081"
    volumes:
      - ./nexus/nexus-data/:/nexus-data/
